### ISSUE TITLE
Move to Go modules

### ISSUE THREAD

**Issue by mre** [mre/riffraff#1]
Golang introduced modules in [1.11](https://github.com/golang/go/wiki/Modules).
It's a nice way to build go packages outside of the `GOPATH` and with proper version management.
Trying Go modules in other projects, I'm very happy with that change and I would also like to adopt Go modules for this project.

Maybe somebody wants to tackle that.
[Here](https://dave.cheney.net/2018/07/14/taking-go-modules-for-a-spin) is what you need to do.

**Comment by jmartin84** [comment]
I can take a look at this
