### ISSUE TITLE
Add goreleaser to Travis CI

### ISSUE THREAD

**Issue by mre** [mre/riffraff#17]
[Goreleaser](https://goreleaser.com/) is a tool for automatically building and deploying Go binaries for different architectures. It's very handy as it avoids doing manual work when releasing new versions.

Would be nice to run goreleaser automatically on every tag.
Here is an example that we can integrate into our Travis CI:
https://goreleaser.com/ci/

Not sure if we need any additional project permissions for pushing the release to Github,
but I'm sure we can find out.

Help appreciated. Accepting PRs here.

**Comment by dnivra26** [comment]
working on it

**Comment by dnivra26** [comment]
@mre builds passing on travis ci? go modules is disabled by default in travis or am i missing something

**Comment by mre** [comment]
See #19
