### ISSUE TITLE
Create a project logo!

### ISSUE THREAD

**Issue by mre** [mre/riffraff#18]
This one goes out to all the creative types: We need a project logo!

I was thinking of a vector graphic of [Riffraff, the butler from the Rocky Horror Picture Show](https://www.google.com/search?tbm=isch&q=riff+raff+rocky+horror+picture+show).
Would be amazing if somebody took Riffraff and vectorized it in the style of the original Jenkins logo:

![jenkins-logo](https://user-images.githubusercontent.com/175809/46664435-52053600-cbc1-11e8-955e-a090fe23bf2d.png)

If anyone wants to tackle this, feel free to add a comment here or send a pull request. 🎨

**Comment by tjkartha** [comment]
I could try!

**Comment by mre** [comment]
Sure! 🎉

**Comment by waynekata** [comment]
https://github.com/mre/riffraff/pull/22

**Comment by nox-moon** [comment]
I also gave it a try. I hope you like it.
![logo](https://user-images.githubusercontent.com/43906683/46915948-c53cec80-cfb3-11e8-87de-89d13402177e.png)

**Comment by mre** [comment]
OMG. That one came out of nowhere.
I love it! So much better than mine.
The lines are much more distinct than in my version and the overall composition of the forms and colors is top-notch. Thank you! 

Could you create a pull request to add it to the `README.md` and add yourself to a new *Credits* section at the bottom of it? Also, could we have a version with the "riffraff" label next to it for the `README.md`? The font is up to you. I'm sure you'll come up with something.

**Comment by mre** [comment]
Alright everybody, I guess we can close this.
Thanks for all the great collaboration and for the awesome final logo. ❤️
